### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by quadflight** [crsherman/nodejs-poolController-mqtt#2]
Is there an option to use user/pass for mqtt ?

Thank you

**Comment by crsherman** [comment]
quadflight,
Try replacing line 47 with the following code:

var host = 'http://your_IP_address_for_mqtt_broker:1883'
var options = {
  username: 'your_username',
  password: 'your_password'
}
var client = mqtt.connect(host, options)

**Comment by rsnodgrass** [comment]
FYI, this is fixed in the latest pull request I just submitted by allowing specifying environment variable with username and password.

https://github.com/crsherman/nodejs-poolController-mqtt/pull/5

**Comment by crsherman** [comment]
Issue fixed with rsnodgrass pull request code.
